### ISSUE TITLE
IRC / Slack link no longer on front page

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-website#49]
It is now only on https://symbiflow.github.io/developers.html page.

**Comment by mithro** [comment]
This should probably be in the front page very close to the top.

**Comment by pgielda** [comment]
Indeed, I was just looking for a link to point @fangism to it but it was not there. Please fix @rw1nkler ASAP.

**Comment by rw1nkler** [comment]
Fixes here: https://github.com/SymbiFlow/symbiflow-website/pull/52

**Comment by rw1nkler** [comment]
This issue can be closed
